services:
  slow-blade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kali
    user: "0:0"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined